import { IUserCreate, ROL } from "../src/domain/entities/user-entity";
import { ITeamCreate } from "./domain/entities/team-entity";

export const userList: IUserCreate[] = [
  { firstName: "Antonio", lastName: "Perez", email: "antonio@gmail.com", password: "12345678", rol: ROL.PLAYER },
  { firstName: "Lara ", lastName: "Alcaráz", email: "lara@gmail.com", password: "87654321", rol: ROL.PLAYER },
  { firstName: "Leon ", lastName: "López", email: "leon@gmail.com", password: "00000000", rol: ROL.PLAYER },
  { firstName: "Virginia ", lastName: "Alonso", email: "virg@gmail.com", password: "11111111", rol: ROL.PLAYER },
  { firstName: "Antonio", lastName: "Perez", email: "antonio@gmail.com", password: "12345678", rol: ROL.PLAYER },
  { firstName: "Juan", lastName: "Gonzalez", email: "juan.gonzalez@example.com", password: "qwerty123", rol: ROL.PLAYER },
  { firstName: "Luis", lastName: "Ramirez", email: "luis.ramirez@example.com", password: "ilovecats", rol: ROL.PLAYER },
  { firstName: "Carlos", lastName: "Hernandez", email: "carlos.hernandez@example.com", password: "football23", rol: ROL.PLAYER },
  { firstName: "Javier", lastName: "Lopez", email: "javier.lopez@example.com", password: "welcome123", rol: ROL.PLAYER },
  { firstName: "Daniel", lastName: "Torres", email: "daniel.torres@example.com", password: "password123", rol: ROL.PLAYER },
  { firstName: "Miguel", lastName: "Gomez", email: "miguel.gomez@example.com", password: "abcde123", rol: ROL.PLAYER },
  { firstName: "Jose", lastName: "Morales", email: "jose.morales@example.com", password: "hello123", rol: ROL.PLAYER },
  { firstName: "Alejandro", lastName: "Castillo", email: "alejandro.castillo@example.com", password: "test123", rol: ROL.PLAYER },
  { firstName: "Francisco", lastName: "Ortega", email: "francisco.ortega@example.com", password: "letmein", rol: ROL.PLAYER },
  { firstName: "Pedro", lastName: "Vargas", email: "pedro.vargas@example.com", password: "123456", rol: ROL.PLAYER },
  { firstName: "Manuel", lastName: "Salazar", email: "manuel.salazar@example.com", password: "password", rol: ROL.PLAYER },
  { firstName: "Hugo", lastName: "Cortes", email: "hugo.cortes@example.com", password: "qwerty", rol: ROL.PLAYER },
  { firstName: "Roberto", lastName: "Valenzuela", email: "roberto.valenzuela@example.com", password: "abc123", rol: ROL.PLAYER },
  { firstName: "Ricardo", lastName: "Vargas", email: "ricardo.vargas@example.com", password: "iloveyou", rol: ROL.PLAYER },
  { firstName: "Arturo", lastName: "Fuentes", email: "arturo.fuentes@example.com", password: "welcome", rol: ROL.PLAYER },
  { firstName: "Enrique", lastName: "Molina", email: "enrique.molina@example.com", password: "123abc", rol: ROL.PLAYER },
  { firstName: "Adrian", lastName: "Rojas", email: "adrian.rojas@example.com", password: "testing123", rol: ROL.PLAYER },
  { firstName: "Fernando", lastName: "Cruz", email: "fernando.cruz@example.com", password: "pass123", rol: ROL.PLAYER },
  { firstName: "Sergio", lastName: "Pacheco", email: "sergio.pacheco@example.com", password: "qwertyuiop", rol: ROL.PLAYER },
  { firstName: "Guillermo", lastName: "Acosta", email: "guillermo.acosta@example.com", password: "1234567890", rol: ROL.PLAYER },
  { firstName: "Emilio", lastName: "Nava", email: "emilio.nava@example.com", password: "testtest", rol: ROL.PLAYER },
  { firstName: "Andrés", lastName: "Cervantes", email: "andres.cervantes@example.com", password: "password1234", rol: ROL.PLAYER },
  { firstName: "Roberto", lastName: "Santos", email: "roberto.santos@example.com", password: "abcde12345", rol: ROL.PLAYER },
  { firstName: "Eduardo", lastName: "Rivas", email: "eduardo.rivas@example.com", password: "hello12345", rol: ROL.PLAYER },
  { firstName: "Gustavo", lastName: "Delgado", email: "gustavo.delgado@example.com", password: "test12345", rol: ROL.PLAYER },
  { firstName: "Ramiro", lastName: "Cano", email: "ramiro.cano@example.com", password: "letmein123", rol: ROL.PLAYER },
  { firstName: "Roberto", lastName: "Vera", email: "roberto.vera@example.com", password: "1234567", rol: ROL.PLAYER },
  { firstName: "Martín", lastName: "Cabrera", email: "martin.cabrera@example.com", password: "password123", rol: ROL.PLAYER },
  { firstName: "Julio", lastName: "Navarro", email: "julio.navarro@example.com", password: "qwerty1234", rol: ROL.PLAYER },
  { firstName: "Héctor", lastName: "Guerrero", email: "hector.guerrero@example.com", password: "ilovecats123", rol: ROL.PLAYER },
  { firstName: "Samuel", lastName: "Paredes", email: "samuel.paredes@example.com", password: "football234", rol: ROL.PLAYER },
  { firstName: "Raul", lastName: "Mendoza", email: "raul.mendoza@example.com", password: "welcome1234", rol: ROL.PLAYER },
  { firstName: "Jorge", lastName: "Escobar", email: "jorge.escobar@example.com", password: "password12345", rol: ROL.PLAYER },
  { firstName: "Agustín", lastName: "Rosas", email: "agustin.rosas@example.com", password: "abcde123456", rol: ROL.PLAYER },
  { firstName: "Maximiliano", lastName: "Castañeda", email: "maximiliano.castaneda@example.com", password: "hello123456", rol: ROL.PLAYER },
  { firstName: "Salvador", lastName: "Velasco", email: "salvador.velasco@example.com", password: "test123456", rol: ROL.PLAYER },
  { firstName: "Alberto", lastName: "Romo", email: "alberto.romo@example.com", password: "letmein1234", rol: ROL.PLAYER },
  { firstName: "Jaime", lastName: "Franco", email: "jaime.franco@example.com", password: "12345678", rol: ROL.PLAYER },
  { firstName: "Rubén", lastName: "Mendez", email: "ruben.mendez@example.com", password: "password1234", rol: ROL.PLAYER },
  { firstName: "Felipe", lastName: "Montes", email: "felipe.montes@example.com", password: "qwerty12345", rol: ROL.PLAYER },
  { firstName: "Benjamín", lastName: "Pineda", email: "benjamin.pineda@example.com", password: "ilovecats1234", rol: ROL.PLAYER },
  { firstName: "Oscar", lastName: "Valencia", email: "oscar.valencia@example.com", password: "football2345", rol: ROL.PLAYER },
  { firstName: "Rogelio", lastName: "Beltrán", email: "rogelio.beltran@example.com", password: "welcome12345", rol: ROL.PLAYER },
  { firstName: "César", lastName: "Palacios", email: "cesar.palacios@example.com", password: "password12345", rol: ROL.PLAYER },
  { firstName: "Leonardo", lastName: "Arroyo", email: "leonardo.arroyo@example.com", password: "abcde1234567", rol: ROL.PLAYER },
  { firstName: "Mario", lastName: "Fuentes", email: "mario.fuentes@example.com", password: "hello1234567", rol: ROL.PLAYER },
  { firstName: "Giovanni", lastName: "Carrasco", email: "giovanni.carrasco@example.com", password: "test1234567", rol: ROL.PLAYER },
  { firstName: "Diego", lastName: "Olvera", email: "diego.olvera@example.com", password: "letmein12345", rol: ROL.PLAYER },
  { firstName: "Israel", lastName: "Amador", email: "israel.amador@example.com", password: "123456789", rol: ROL.PLAYER },
  { firstName: "Ernesto ", lastName: "Sevilla", email: "ernesto@gmail.com", password: "22222222", rol: ROL.MANAGER },
  { firstName: "Ernesto", lastName: "Sevilla", email: "ernesto@gmail.com", password: "22222222", rol: ROL.MANAGER },
  { firstName: "Javier", lastName: "García", email: "javier.garcia@example.com", password: "12345678", rol: ROL.MANAGER },
  { firstName: "Luis", lastName: "Fernández", email: "luis.fernandez@example.com", password: "password123", rol: ROL.MANAGER },
  { firstName: "Roberto", lastName: "Mendoza", email: "roberto.mendoza@example.com", password: "qwerty123", rol: ROL.MANAGER },
  { firstName: "Carlos", lastName: "Martínez", email: "carlos.martinez@example.com", password: "ilovecats", rol: ROL.MANAGER },
  { firstName: "Juan", lastName: "Hernández", email: "juan.hernandez@example.com", password: "abcdefg", rol: ROL.MANAGER },
  { firstName: "Ana ", lastName: "Obregón", email: "ana@gmail.com", password: "33333333", rol: ROL.MANAGER },
  { firstName: "Francisco ", lastName: "Bueno", email: "frank@gmail.com", password: "44444444", rol: ROL.MANAGER },
  { firstName: "Toni ", lastName: "Moreno", email: "toni@gmail.com", password: "55555555", rol: ROL.MANAGER },
  { firstName: "Antonio", lastName: "Alcaráz", email: "admin@gmail.com", password: "55555555", rol: ROL.ADMIN },
];

export const teamList: ITeamCreate[] = [
  { name: "Real Madrid CF", initials: "RMC", image: "" },
  { name: "Barcelona FC", initials: "BCF", image: "" },
  { name: "Cadiz FC", initials: "CDF", image: "" },
  { name: "Real Betis", initials: "RBC", image: "" },
  { name: "Sevilla FC", initials: "SFC", image: "" },
  { name: "Valencia CF", initials: "VCF", image: "" },
  { name: "Real Sociedad", initials: "RSC", image: "" },
  { name: "Atlético de Madrid", initials: "ATM", image: "" },
  { name: "Girona FC", initials: "GFC", image: "" },
  { name: "Getafe FC", initials: "GEC", image: "" },
]
